### PR TITLE
Support API to get service metrics

### PR DESCRIPTION
**Pull request by waniji**
I added a method to get service metrics value.
https://mackerel.io/ja/api-docs/entry/service-metrics#get

### CODE REVIEW

**Comment by myfinder** [comment]
Thank you! It looks like good to me.
@papix do you think about this p-r?

**Comment by papix** [comment]
@myfinder LGTM!

**Comment by waniji** [comment]
@myfinder How is the current status going?

**Comment by papix** [comment]
@waniji I'm really sorry... I merged your pull request.
It will be released soon!

**Comment by waniji** [comment]
Thank you!

**Pull request merged**
