### PR TITLE
Extended hosts and host metrics api methods

### PR DESCRIPTION
**Pull request by yoheimuta**
I want to call [/api/v0/hosts.json](https://mackerel.io/ja/api-docs/entry/hosts#list) with any query parameters and [/api/v0/hosts/{host_id}/metrics](https://mackerel.io/ja/api-docs/entry/host-metrics#get).

Usage examples:

```perl
my @args = (service => "service", role => "bastion", 
    role => "batch", status => "working");
my $content = $mackerel->get_hosts(\@args);
```

```perl
my $host_id = "2RnaLGypmBJ"; 
my $args = { name => 'loadavg5', from => '1478744400', to => '1479303590' }; 
my $content = $mackerel->get_host_metrics($host_id, $args);
```

### CODE REVIEW

**Comment by yoheimuta** [comment]
sorry, I'm going to fix tests.

**Comment by yoheimuta** [comment]
> sorry, I'm going to fix tests.

It's an unrelated issue https://github.com/myfinder/webservice-mackerel/issues/6 with this pr, so I reopen it.

**Comment by cou929** [comment]
@yoheimuta The diff is looks good but CI has been failed as you mentioned.
I commented to #6 about that.

**Comment by yoheimuta** [comment]
@cou929 Thank you for advice. 135ee56 fixes a CI failure.

**Comment by cou929** [comment]
@yoheimuta I reviewed 135ee56 and It's okay.
I think you can merge this p-r.
Thank you!

**Comment by yoheimuta** [comment]
Thanks !

**Pull request merged**
